# Change these first
owner: bigbang1112 # Your GitHub organization or username, where this repository lives
repo: bigbang1112eu-uptime # The name of this repository

sites:
  - name: bigbang1112.eu (redirect to cz)
    url: https://bigbang1112.eu
    slug: bigbang1112-eu
  - name: challenge.bigbang1112.eu
    url: https://challenge.bigbang1112.eu
    
assignees: # Users to assign downtime issues (optional)
  - BigBang1112

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bigbang1112.eu
  #baseUrl: /bigbang1112eu-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.bigbang1112.eu
  introTitle: "**BigBang1112.eu** status page"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
